name: torch-py11
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiobotocore=2.19.0=py311h06a4308_0
  - aiohappyeyeballs=2.4.4=py311h06a4308_0
  - aiohttp=3.11.10=py311h5eee18b_0
  - aioitertools=0.7.1=pyhd3eb1b0_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.16=py311h06a4308_0
  - altair=5.5.0=py311h06a4308_0
  - anaconda=2025.06=py311_mkl_2
  - anyio=4.7.0=py311h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_1
  - arrow=1.3.0=py311h06a4308_0
  - arrow-cpp=19.0.0=h865e1df_2
  - astroid=3.3.8=py311h06a4308_0
  - astropy=7.0.0=py311h5eee18b_0
  - astropy-iers-data=0.2025.1.13.0.34.51=py311h06a4308_0
  - asttokens=3.0.0=py311h06a4308_0
  - async-lru=2.0.4=py311h06a4308_0
  - asyncssh=2.17.0=py311h06a4308_0
  - atomicwrites=1.4.0=py_0
  - attrs=24.3.0=py311h06a4308_0
  - automat=24.8.1=py311h06a4308_0
  - autopep8=2.0.4=pyhd3eb1b0_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - babel=2.16.0=py311h06a4308_0
  - backports.tarfile=1.2.0=py311h06a4308_0
  - bcrypt=4.3.0=py311h4aa5aa6_0
  - beautifulsoup4=4.12.3=py311h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=24.10.0=py311h06a4308_0
  - blas=1.0=mkl
  - bleach=6.2.0=py311h06a4308_0
  - blinker=1.9.0=py311h06a4308_0
  - blosc=1.21.3=h6a678d5_0
  - bokeh=3.6.2=py311h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - botocore=1.36.3=py311h06a4308_0
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - c-blosc2=2.17.1=h4257ac4_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cachetools=5.5.1=py311h06a4308_0
  - certifi=2025.4.26=py311h06a4308_0
  - cffi=1.17.1=py311h1fdaa30_1
  - chardet=4.0.0=py311h06a4308_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py311h06a4308_0
  - cloudpickle=3.0.0=py311h06a4308_0
  - colorcet=3.1.0=py311h06a4308_0
  - comm=0.2.1=py311h06a4308_0
  - constantly=23.10.4=py311h06a4308_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - cookiecutter=2.6.0=py311h06a4308_0
  - cryptography=44.0.1=py311h7825ff9_0
  - cssselect=1.2.0=py311h06a4308_0
  - curl=8.12.1=h251f7ec_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cytoolz=1.0.1=py311h5eee18b_0
  - dask=2025.2.0=py311h06a4308_0
  - dask-core=2025.2.0=py311h06a4308_0
  - dask-expr=2.0.0=py311h06a4308_0
  - datashader=0.18.0=py311h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py311h06a4308_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.8=py311h06a4308_0
  - distributed=2025.2.0=py311h06a4308_0
  - docstring-to-markdown=0.11=py311h06a4308_0
  - docutils=0.21.2=py311h06a4308_0
  - et_xmlfile=1.1.0=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.17.0=py311h06a4308_0
  - flake8=7.1.1=py311h06a4308_0
  - flask=3.1.0=py311h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py311h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py311h5eee18b_0
  - fsspec=2025.3.2=py311he3bba80_0
  - gflags=2.2.2=h6a678d5_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.43=py311h06a4308_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - greenlet=3.1.1=py311h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.16.0=py311h06a4308_0
  - h5py=3.12.1=py311h5842655_1
  - hdf5=1.14.5=h2b7332f_2
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.20.2=py311h06a4308_0
  - httpcore=1.0.9=py311h06a4308_0
  - httpx=0.28.1=py311h06a4308_0
  - hvplot=0.11.3=py311h06a4308_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - imageio=2.37.0=py311h06a4308_0
  - imagesize=1.4.1=py311h06a4308_0
  - imbalanced-learn=0.13.0=py311h06a4308_0
  - importlib-metadata=8.5.0=py311h06a4308_0
  - incremental=24.7.2=pyhd3eb1b0_0
  - inflection=0.5.1=py311h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=2.0.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.29.5=py311h06a4308_1
  - ipython=8.30.0=py311h06a4308_0
  - ipywidgets=8.1.5=py311h06a4308_0
  - isort=6.0.1=py311h06a4308_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.3.2=py311h06a4308_0
  - itsdangerous=2.2.0=py311h06a4308_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jaraco.context=6.0.0=py311h06a4308_0
  - jaraco.functools=4.1.0=py311h06a4308_0
  - jedi=0.19.2=py311h06a4308_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=1.1.3=py311h4aa5aa6_0
  - jinja2=3.1.6=py311h06a4308_0
  - jmespath=1.0.1=py311h06a4308_0
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jq=1.7.1=h5eee18b_0
  - json5=0.9.25=py311h06a4308_0
  - jsonschema=4.23.0=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter=1.1.1=py311h06a4308_0
  - jupyter-lsp=2.2.5=py311h06a4308_0
  - jupyter_client=8.6.3=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - jupyter_events=0.12.0=py311h06a4308_0
  - jupyter_server=2.15.0=py311h06a4308_0
  - jupyter_server_terminals=0.5.3=py311h06a4308_0
  - jupyterlab=4.3.4=py311h06a4308_0
  - jupyterlab-variableinspector=3.2.4=py311h06a4308_0
  - jupyterlab_pygments=0.3.0=py311h06a4308_0
  - jupyterlab_server=2.27.3=py311h06a4308_0
  - jupyterlab_widgets=3.0.13=py311h06a4308_0
  - keyring=25.6.0=py311h06a4308_0
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lazy_loader=0.4=py311h06a4308_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=hc99497a_0
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - linkify-it-py=2.0.0=py311h06a4308_0
  - llvmlite=0.44.0=py311hc1e8f15_1
  - locket=1.0.0=py311h06a4308_0
  - lxml=5.3.0=py311h57af460_1
  - lz4=4.3.2=py311h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - markdown=3.8=py311h06a4308_0
  - markdown-it-py=2.2.0=py311h06a4308_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.10.0=py311h06a4308_0
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mdit-py-plugins=0.3.0=py311h06a4308_0
  - mdurl=0.1.0=py311h06a4308_0
  - mistune=3.1.2=py311h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - more-itertools=10.3.0=py311h06a4308_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - msgpack-python=1.0.7=py311h6a678d5_0
  - multidict=6.1.0=py311h5eee18b_0
  - multipledispatch=0.6.0=py311h06a4308_0
  - mypy=1.14.1=py311h5eee18b_0
  - mypy_extensions=1.0.0=py311h06a4308_0
  - mysql=8.4.0=h721767e_2
  - narwhals=1.31.0=py311h06a4308_1
  - nbclient=0.10.2=py311h06a4308_0
  - nbconvert=7.16.6=py311h06a4308_0
  - nbconvert-core=7.16.6=py311h06a4308_0
  - nbconvert-pandoc=7.16.6=py311h06a4308_0
  - nbformat=5.10.4=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - networkx=3.4.2=py311h06a4308_0
  - nltk=3.9.1=py311h06a4308_0
  - notebook=7.3.2=py311h06a4308_1
  - notebook-shim=0.2.4=py311h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numba=0.61.0=py311h6a678d5_1
  - numexpr=2.10.1=py311h3c60e43_0
  - numpy=2.1.3=py311h08b1b3b_0
  - numpy-base=2.1.3=py311hf175353_0
  - numpydoc=1.7.0=py311h06a4308_0
  - oniguruma=6.9.7.1=h27cfd23_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openpyxl=3.1.5=py311h5eee18b_1
  - openssl=3.0.16=h5eee18b_0
  - orc=2.1.1=hd396ef6_0
  - overrides=7.4.0=py311h06a4308_0
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.3=py311h6a678d5_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=1.7.0=py311h06a4308_0
  - param=2.2.0=py311h06a4308_0
  - parsel=1.8.1=py311h06a4308_0
  - parso=0.8.4=py311h06a4308_0
  - partd=1.4.2=py311h06a4308_0
  - pathspec=0.10.3=py311h06a4308_0
  - patsy=1.0.1=py311h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.1.0=py311hac6e08b_1
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.7=py311h06a4308_0
  - plotly=5.24.1=py311h92b7b1e_1
  - pluggy=1.5.0=py311h06a4308_0
  - ply=3.11=py311h06a4308_0
  - prometheus_client=0.21.1=py311h06a4308_0
  - prompt-toolkit=3.0.43=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - propcache=0.3.1=py311h5eee18b_0
  - protego=0.4.0=py311h06a4308_0
  - protobuf=5.29.3=py311he621ea3_0
  - psutil=5.9.0=py311h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=9.0.0=py311h06a4308_0
  - pyarrow=19.0.0=py311h6a678d5_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.12.1=py311h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.5.0=py311h06a4308_0
  - pycurl=7.45.6=py311haf51bff_0
  - pydispatcher=2.0.5=py311h06a4308_2
  - pydocstyle=6.3.0=py311h06a4308_0
  - pyerfa=2.0.1.5=py311h5eee18b_0
  - pyflakes=3.2.0=py311h06a4308_0
  - pygithub=2.4.0=py311h06a4308_0
  - pygments=2.19.1=py311h06a4308_0
  - pyjwt=2.10.1=py311h06a4308_0
  - pylint=3.3.5=py311h06a4308_0
  - pylint-venv=3.0.3=py311h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py311h5eee18b_1
  - pyodbc=5.2.0=py311h6a678d5_0
  - pyopenssl=25.0.0=py311h06a4308_0
  - pyparsing=3.2.0=py311h06a4308_0
  - pyqt=5.15.10=py311h6a678d5_1
  - pyqt5-sip=12.13.0=py311h5eee18b_1
  - pyqtwebengine=5.15.10=py311h6a678d5_1
  - pysocks=1.7.1=py311h06a4308_0
  - pytables=3.10.2=py311hc48ae32_2
  - pytest=8.3.4=py311h06a4308_0
  - python=3.11.13=h1a3bd86_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.20.0=py311h06a4308_0
  - python-json-logger=3.2.1=py311h06a4308_0
  - python-lmdb=1.6.2=py311h6a678d5_0
  - python-lsp-black=2.0.0=py311h06a4308_1
  - python-lsp-jsonrpc=1.1.2=pyhd3eb1b0_0
  - python-lsp-server=1.12.2=py311he3bba80_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytoolconfig=1.2.6=py311h06a4308_0
  - pytz=2024.1=py311h06a4308_0
  - pyuca=1.2=py311h06a4308_1
  - pyviz_comms=3.0.2=py311h06a4308_0
  - pywavelets=1.8.0=py311h5eee18b_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=26.2.0=py311h6a678d5_0
  - qdarkstyle=3.2.3=pyhd3eb1b0_0
  - qstylizer=0.2.2=py311h06a4308_0
  - qt-main=5.15.2=hb6262e9_12
  - qt-webengine=5.15.9=he2071f7_8
  - qtawesome=1.4.0=py311h06a4308_0
  - qtconsole=5.6.1=py311h06a4308_1
  - qtpy=2.4.1=py311h06a4308_0
  - queuelib=1.6.2=py311h06a4308_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py311h06a4308_0
  - regex=2024.11.6=py311h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - requests-file=2.1.0=py311h06a4308_0
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rich=13.9.4=py311h06a4308_0
  - roman-numerals-py=3.1.0=py311h06a4308_0
  - rope=1.13.0=py311h06a4308_0
  - rpds-py=0.22.3=py311h4aa5aa6_0
  - rtree=1.0.1=py311h06a4308_0
  - s2n=1.3.27=hdbd6064_0
  - s3fs=2025.3.2=py311h06a4308_0
  - scikit-image=0.25.0=py311h6a678d5_0
  - scikit-learn=1.6.1=py311h6a678d5_0
  - scipy=1.15.3=py311h525edd1_0
  - scrapy=2.12.0=py311h06a4308_1
  - seaborn=0.13.2=py311h06a4308_3
  - secretstorage=3.3.1=py311h06a4308_1
  - send2trash=1.8.2=py311h06a4308_1
  - service_identity=24.2.0=py311h06a4308_0
  - setuptools=72.1.0=py311h06a4308_0
  - sip=6.7.12=py311h6a678d5_1
  - six=1.17.0=py311h06a4308_0
  - sklearn-compat=0.1.3=py311h06a4308_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py311h06a4308_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py311h06a4308_0
  - sphinx=8.2.3=py311h5eee18b_0
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - spyder=6.0.7=py311h06a4308_1
  - spyder-kernels=3.0.5=py311he3bba80_0
  - sqlalchemy=2.0.39=py311h00e1ef3_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.4=py311h5eee18b_0
  - streamlit=1.45.1=py311h06a4308_1
  - superqt=0.7.3=py311he3bba80_0
  - sympy=1.13.3=py311h06a4308_1
  - tabulate=0.9.0=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tblib=3.1.0=py311h06a4308_0
  - tenacity=9.0.0=py311h06a4308_0
  - terminado=0.17.1=py311h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.6.3=py311h92b7b1e_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2025.2.18=py311h06a4308_0
  - tinycss2=1.4.0=py311h06a4308_0
  - tk=8.6.14=h993c535_1
  - tldextract=5.1.2=py311h06a4308_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py311h06a4308_0
  - tomlkit=0.13.2=py311h06a4308_0
  - toolz=1.0.0=py311h06a4308_0
  - tornado=6.5.1=py311h5eee18b_0
  - tqdm=4.67.1=py311h92b7b1e_0
  - traitlets=5.14.3=py311h06a4308_0
  - twisted=24.11.0=py311h06a4308_0
  - typing-extensions=4.12.2=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - uc-micro-py=1.0.1=py311h06a4308_0
  - ujson=5.10.0=py311h6a678d5_1
  - unicodedata2=15.1.0=py311h5eee18b_1
  - unidecode=1.3.8=py311h06a4308_0
  - unixodbc=2.3.11=h5eee18b_0
  - urllib3=2.3.0=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - w3lib=2.1.2=py311h06a4308_0
  - watchdog=4.0.2=py311h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - werkzeug=3.1.3=py311h06a4308_0
  - whatthepatch=1.0.2=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - widgetsnbextension=4.0.13=py311h06a4308_0
  - wrapt=1.17.0=py311h5eee18b_0
  - wurlitzer=3.0.2=py311h06a4308_0
  - xarray=2025.4.0=py311h06a4308_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xyzservices=2022.9.0=py311h06a4308_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.40.2=py311h06a4308_0
  - yarl=1.18.0=py311h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zict=3.0.0=py311h06a4308_0
  - zipp=3.21.0=py311h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zlib-ng=2.0.7=h5eee18b_0
  - zope=1.0=py311h06a4308_1
  - zope.interface=7.1.1=py311h5eee18b_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.1
      - corner==2.2.3
      - deprecation==2.1.0
      - dynesty==3.0.0
      - emcee==3.1.6
      - lightning-utilities==0.15.2
      - ml-collections==1.1.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - pyg-lib==0.4.0+pt28cu126
      - pytorch-lightning==2.5.5
      - tarp==0.1.1
      - torch==2.8.0+cu126
      - torch-cluster==1.6.3+pt28cu126
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt28cu126
      - torch-sparse==0.6.18+pt28cu126
      - torch-spline-conv==1.2.2+pt28cu126
      - torchmetrics==1.8.2
      - torchvision==0.23.0+cu126
      - triton==3.4.0
      - zuko==1.5.0
prefix: /home/tvnguyen/miniconda3/envs/torch-py11
